### ISSUE TITLE
Takes very long to start if no Internet is available

### ISSUE THREAD

**Issue by fisch3r** [EXXETA/correomqtt#134]
**Describe the bug**
When no Internet is available Correo takes very long to start since it checks for updates (> 2 Minutes)

**To Reproduce**
1. Disconnect your computer from the internet and connect to a network without internet
2. Start Correo
3. Takes very long to start

**Expected behavior**
There is a connection timeout of 5 seconds for the update request or as an alternative a button to cancel the request for updates.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 0.14.2

**Comment by farion** [comment]
Yes, we do two types of requests during startup.

At first, we check if there is an update on github. This is done with HttpURLConnection, where the default timeout is 2 minutes.

Additional we check the plugin repo, which is at least one request. This is done by PF4J, which is using URL, which has a default timeout of 20 seconds. So the wait time is 2:20 minutes, which seems to fit to your report.

As the plugin repo files are also live on github we may skip the whole plugin check in case the version check did fail. So the version check will act as "github health check". I propose to use a very short timeout (5 seconds as you mentioned). Those checks and updates are not mandatory. The app will still run and will just do it next start up.
