### ISSUE TITLE
List of available plugins on github

### ISSUE THREAD

**Issue by fisch3r** [EXXETA/correomqtt#16]
Create a list of the available plugins for correo with a short description and link to the plugin repository

**Comment by farion** [comment]
* Upload Correo Main jar without dependencies to Maven Central: https://github.com/stefanbirkner/travis-deploy-to-maven-central
* Build plugins itself using correo from maven central.
* Create one plugins.json per correo version in a new repo (correomqtt-pluginrepo) with links to the plugin release jars.
* Make Correo use the matching plugins.json as update url.
* Remove bundled plugins from delivery.

**Comment by raujonas** [comment]
- [x] Correo main jar to maven central
- [x] Build plugins separate
- [x] plugin.json per correo version
- [x] Make correo use new repo
- [x] Remove bundled plugins
- [x] Adding list with descriptions
