### ISSUE TITLE
Create a plugin for the systopic feature

### ISSUE THREAD

**Issue by fisch3r** [EXXETA/correomqtt#24]

**Comment by farion** [comment]
- Zusätzlicher Extension-Point um Elemente in die Haupttoolbar einer Verbindung hinzufügen zu können.
- Hinzufügen des Sys-Topic-Buttons durch das Plugin.
- Anzeigen und Steuern des Fensters durch das Plugin (kein spezieller Plugin-Code hier notwendig)
- Entfernen des Features aus dem Core
- Aktualisieren der Plugin-Liste (für neue Version)

**Comment by farion** [comment]
Repo for the new Plugin: https://github.com/EXXETA/correomqtt-plugin-systopic
