### ISSUE TITLE
Move plugins that throw exceptions during startup

### ISSUE THREAD

**Issue by farion** [EXXETA/correomqtt#31]
- Store the current version in config
- If the plugin loader throws an exception move the plugins folder into a new folder called plugins.disabled.{oldversion} 
- In case of conflict add an counter plugins.disabled.{oldversion}.1 and so on.

**Comment by raujonas** [comment]
- [x] Store the current version in config
- [x] If the plugin loader throws an exception move the plugins folder into a new folder called plugins.disabled.{oldversion}
- [x] In case of conflict add an counter plugins.disabled.{oldversion}.1 and so on.

- [x] Improved progress hints in preloader and added loading indicator

**Comment by farion** [comment]
- Folder renamed to plugins.disabled.{date}
- Due to an unresolved bug in PF4J (https://github.com/pf4j/pf4j/pull/356) Correo will place a file called "broken" inside the plugins folder and force a restart on incompatible plugins on windows. On startup plugins will be moved than BEFORE plugin system is started. On non-windows systems the plugins will be moved without a restart.
