### ISSUE TITLE
Issue using version v0.10.0 and above on MacOS High Sierra v10.13.6

### ISSUE THREAD

**Issue by staxDB** [EXXETA/correomqtt#34]
Hey there,
When I try to install newer versions (tested with v0.10.0, v0.11.0 and v0.11.1) I always get the following error message on macOS:
<img width="439" alt="issue_onMacHighSierra" src="https://user-images.githubusercontent.com/8705799/78758064-cfa82e80-797d-11ea-9eb5-06a15ee675b9.png">

Version v0.9.0 works fine

**Comment by farion** [comment]
This is caused by gatekeeper. You have to un-quarantine correo.

`xattr -d com.apple.quarantine /Applications/CorreoMQTT.app`
See: https://github.com/EXXETA/correomqtt#note-for-osx
