### ISSUE TITLE
Checkbox to publish messages without encoding them as Base64

### ISSUE THREAD

**Issue by staxDB** [EXXETA/correomqtt#63]
Atm the publish client sends all messages as Base64 string. For example:
Original message: 
```json
{
 "message": "Just a simple test"
}
```
would be published as 
```
ewogIm1lc3NhZ2UiOiAiSnVzdCBhIHNpbXBsZSB0ZXN0Igp9
```

It would be great if publish gave you the ability to send messages without Base64

**Comment by raujonas** [comment]
Hi! Have you tried to deactivate the base64 plugin in the plugin settings (Tools - Manage plugins)? I think it also encodes outgoing messages.

![grafik](https://user-images.githubusercontent.com/25148277/99785931-26820300-2b1e-11eb-90a8-5da6aa957a05.png)

**Comment by staxDB** [comment]
This solved my issue, thanks 👍

**Comment by raujonas** [comment]
Nice! 

@farion I think it would make sense to disable this plugin per default in the future, what do you think?
