### ISSUE TITLE
Add Import- / Export Connections

### ISSUE THREAD

**Issue by farion** [EXXETA/correomqtt#65]
TBD

**Comment by squashi6** [comment]
**Is your feature request related to a problem? Please describe.** 
Currently there is no option to export configured connections. If you want to use the same connections on a different client, the connections need to be created again by hand. 

**Describe the solution you'd like**
There should be an option to export connections in a .json file and store them on your device. There also needs to be an option to import the exported connections to use them on a different client. The export function also needs an option to encrypt the export with a password. This is neccessary if the connections include login data like usernames and passwords.

- [x] There is a button to export connection. 
- [ ] Clicking the button opens a menu to select the connections to be exported.
- [ ] When clicking the accept button on the selection menu a file explorer opens to save the connections to a location on the users file system.
- [ ] There is an option to encrypt the exported file with a password.
- [ ] There is a button to import connections. 
- [ ] On clicking the import button the users file system opens to select a .json file for importing connections.

**Comment by farion** [comment]
Already implemented
