### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [EXXETA/correomqtt#84]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fisch3r** [comment]
Sorry for the late response. Our project now also has a SECURITY.md. So feel free to contact us.

**Comment by JamieSlome** [comment]
@fisch3r - no worries. Just a heads up that you can view the report directly here:

https://huntr.dev/bounties/6c65d6c2-9fa4-4625-88fe-64a2cb31e638/

It is private and only accessible to maintainers with repository write permissions.
